name: Build and Push Docker Image to Scaleway

on:
  push:
    branches:
      - main

jobs:
  build_API:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Scaleway Container Registry
        run: echo "${{ secrets.SCW_REGISTRY_PASSWORD }}" | docker login rg.fr-par.scw.cloud/namespace-karl-dambreville -u nologin --password-stdin

      - name: Build Docker Image
        run: docker build -t devops-final-back ./back --build-arg DEFAULT_ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag devops-final-back rg.fr-par.scw.cloud/namespace-karl-dambreville/devops-final-back:latest

      - name: Push Docker image
        run: docker push rg.fr-par.scw.cloud/namespace-karl-dambreville/devops-final-back:latest
          

  deploy_API:
    needs: build_API
    runs-on: ubuntu-latest
    outputs:
      backend_url: ${{ steps.deploy_container.outputs.container_url }}
      
    steps:
        - name: Deploy container on Scaleway
          uses: scaleway/action-scw@v0.0.2
          with:
            access-key: SCWEMRGW0E33KKBZD17Z
            secret-key: "${{ secrets.SCW_REGISTRY_PASSWORD }}"
            default-project-id: 72e49469-ee5f-4f2f-b2b5-9c17b99d0f28
            default-organization-id: 909c2e48-12fc-47bf-b8ef-360a60b07500
            save-config: true
          
        - name: deploy on scw
          run: |
            RESULT=$(scw container container create name=deploy-back \ 
            namespace-id=c18c7dc3-312e-40d1-9275-203f49e3ca5a \
            registry-image=rg.fr-par.scw.cloud/namespace-karl-dambreville/devops-final-back:latest \
            port=3000 max-scale=1 cpu-limit=100 memory-limit=128 \
            -o json)
            
            URL=$(echo "$RESULT" | jq -r '.domain_name')

            echo $URL
            echo "container_url=$URL" >> "$GITHUB_ENV"
            echo "container_url=$URL" >> "$GITHUB_OUTPUT"






  build_front:
    runs-on: ubuntu-latest
    needs: deploy_API

    steps:
          - name: Checkout Repository
            uses: actions/checkout@v3
    
          - name: Login to Scaleway Container Registry
            run: echo "${{ secrets.SCW_REGISTRY_PASSWORD }}" | docker login rg.fr-par.scw.cloud/namespace-karl-dambreville -u nologin --password-stdin
    
          - name: Build Docker Image
            run: docker build -t devops-final-front --build-arg VITE_API_URL="https://${{ needs.deploy_API.outputs.backend_url }}/" ./front

          - name: Tag Docker Image
            run: docker tag devops-final-front rg.fr-par.scw.cloud/namespace-karl-dambreville/devops-final-front:latest

          - name: Push Docker image
            run: docker push rg.fr-par.scw.cloud/namespace-karl-dambreville/devops-final-front:latest

            
  deploy_API_FRONT:
      needs: build_front
      runs-on: ubuntu-latest
      steps:
          - name: Deploy container on Scaleway
            uses: scaleway/action-scw@v0.0.2
            with:
              access-key: SCWEMRGW0E33KKBZD17Z
              secret-key: "${{ secrets.SCW_REGISTRY_PASSWORD }}"
              default-project-id: 72e49469-ee5f-4f2f-b2b5-9c17b99d0f28
              default-organization-id: 909c2e48-12fc-47bf-b8ef-360a60b07500
              save-config: true
            
          - name: deploy on scw
            run: |
                scw container container create name=deploy-front \
                namespace-id=c18c7dc3-312e-40d1-9275-203f49e3ca5a \
                registry-image=rg.fr-par.scw.cloud/namespace-karl-dambreville/devops-final-front:latest \
                port=80 max-scale=1 cpu-limit=100 memory-limit=128 
